const messages = {
  en: {
    chat: 'Chat', personalData: 'Personal data', mood: 'Mood check-in', knowledge: 'Knowledge & RAG', operations: 'Operations', privacy: 'Privacy & export',
    newChat: 'New chat', conversations: 'Conversations', noChats: 'No saved chats yet.', logout: 'Log out', renameConversation: 'Rename conversation', deleteConversation: 'Delete conversation', deleteConversationConfirm: 'Delete this conversation permanently?', conversationTitle: 'Conversation title', saveTitle: 'Save title', cancel: 'Cancel',
    theme: 'Theme', language: 'Language', light: 'Light', dark: 'Dark', system: 'System', english: 'English', chinese: 'Chinese',
    newConversation: 'New conversation', connected: 'Connected to', preferences: 'Preferences', hidePreferences: 'Hide preferences',
    settingsCopy: 'These options are sent with each reply. API keys remain in this browser tab only.', provider: 'Provider', model: 'Model', baseUrl: 'Base URL', apiKey: 'API key', serverDefault: 'Use server default', optionalEndpoint: 'Optional provider endpoint', tabOnly: 'Only held in this tab', knowledgeRetrieval: 'Knowledge retrieval', knowledgeHint: 'Include matching RAG references', styleReference: 'Style reference', styleHint: 'Apply the selected style corpus', temperature: 'Temperature',
    welcomeTitle: 'How are you feeling today?', welcomeText: 'You can start with a question, a reflection, or a small thing that is on your mind.', talkPrompt: 'Talk through a feeling', planPrompt: 'Plan the next step', composer: 'Message Serenova',
    stillWaiting: 'The provider is still working. You can stop this reply without refreshing the page.', stopGenerating: 'Stop generating', requestCancelled: 'Generation stopped.', emptyResponse: 'The model finished without returning any text.', replyFailed: 'Unable to generate a reply.', retryGeneration: 'Regenerate', copyReply: 'Copy reply', copied: 'Reply copied.', copyFailed: 'Unable to copy the reply.', error_provider_api_key_missing: 'The selected provider has no API key configured.', error_provider_authentication: 'The provider rejected its credentials. Check the API key.', error_provider_rate_limit: 'The provider is rate-limiting requests. Please retry shortly.', error_provider_timeout: 'The provider timed out. Please retry.', error_provider_network: 'The provider network connection failed. Please retry.', error_provider_server: 'The provider is temporarily unavailable. Please retry.', error_local_model_failed: 'The local model could not complete this reply. Please retry.', error_rate_limit_exceeded: 'This account has reached its request-rate limit. Please retry shortly.', error_daily_budget_exceeded: 'Today\'s API budget has been reached.', error_monthly_budget_exceeded: 'This month\'s API budget has been reached.', error_provider_not_supported: 'The selected provider is not supported.', error_generation_failed: 'The model could not complete this reply. Please retry.',
    loginTitle: 'A quieter place to think.', loginText: 'Continue your conversations with memory, knowledge, and personal context kept under your control.', welcomeBack: 'Welcome back', loginHelp: 'Sign in to open your private workspace.', userId: 'User ID', password: 'Access password', signIn: 'Sign in',
    refresh: 'Refresh', loading: 'Loading', save: 'Save check-in', delete: 'Delete', upload: 'Upload', rebuild: 'Rebuild', search: 'Search', runEvaluation: 'Run evaluation', downloadExport: 'Download export', deleteMyData: 'Delete my data', jobs: 'Background jobs', noJobs: 'No recent background jobs.', queued: 'Queued', running: 'Running', succeeded: 'Completed', failed: 'Failed', jobQueued: 'Submitted to the background queue.',
    memoryTitle: 'Personal data', memoryDescription: 'A transparent view of the memories currently available to your assistant.', memoryQuality: 'Memory quality', stableProfile: 'Stable profile', longTermMemory: 'Long-term memory', longTermDescription: 'Review, correct, add, or remove facts the assistant may reference.', addMemory: 'Add memory', editMemory: 'Edit memory', deleteMemory: 'Delete memory', saveMemory: 'Save memory', memoryText: 'Memory text', memoryRequired: 'Memory text is required.', noLongTerm: 'No long-term memories yet.', recentEvents: 'Recent memory events', noStable: 'No stable profile entries yet.', noEvents: 'No memory events yet.',
    moodTitle: 'Mood check-in', moodDescription: 'Record a small signal today, then use the weekly view to notice patterns over time.', todayCheckin: "Today's check-in", moodLabel: 'Mood', moodPlaceholder: 'e.g. calm, anxious, hopeful', intensity: 'Intensity', note: 'Note', notePlaceholder: 'Optional context', weeklyTrend: 'Weekly mood trend', recentCheckins: 'Recent check-ins', noCheckins: 'No check-ins yet.',
    noWeeklySummary: 'No weekly summary available.', noQualityResult: 'No quality result available.', noMatchingChunks: 'No matching chunks.', noEvaluation: 'No saved evaluation report.',
    history: 'History', emotion: 'Emotion', longTerm: 'Long-term', interests: 'Interests',
    knowledgeTitle: 'Knowledge & RAG', knowledgeDescription: 'Inspect indexed documents, test retrieval quality, and run your saved evaluation set.', status: 'Status', documents: 'Documents', quality: 'Quality', chunks: 'Chunks', release: 'Release', releaseGate: 'Release gate', indexedDocuments: 'Indexed documents', qualityReport: 'Quality report', noDocuments: 'No documents are indexed.', retrievalCheck: 'Retrieval check', retrievalPlaceholder: 'Ask a question to test retrieval', ragEvaluation: 'RAG evaluation',
    operationsTitle: 'Operations dashboard', operationsDescription: 'Monitor API reliability, provider failures, background jobs, and alert state for this deployment.', selectedWindow: 'Selected window', requests: 'Requests', failureRate: 'Failure rate', averageLatency: 'Average latency', activeAlerts: 'Active alerts', alerts: 'Alerts', providerFailures: 'Provider failures', jobFailures: 'Background job failures', noAlerts: 'No active or recent alerts.', noProviderFailures: 'No provider failures in this window.', noJobFailures: 'No background job failures in this window.', accessDenied: 'This account is not allowed to view operational data.',
    privacyTitle: 'Privacy & export', privacyDescription: 'See what is stored for your account, create a portable export, or permanently remove your data.', exportTitle: 'Export your data', exportDescription: 'Download conversations, memories, Mood Check-ins, and other user-owned records as JSON. Access passwords, API keys, and .env secrets are excluded.', deleteTitle: 'Delete all data', deleteDescription: "This removes the authenticated user's stored data. Shared knowledge-base documents are not affected.", deletePlaceholder: 'Type DELETE to confirm.',
  },
  zh: {
    chat: '聊天', personalData: '个人数据', mood: '心情记录', knowledge: '知识库与 RAG', operations: '运维', privacy: '隐私与导出',
    newChat: '新建对话', conversations: '历史会话', noChats: '暂无已保存的会话。', logout: '退出登录', renameConversation: '重命名对话', deleteConversation: '删除对话', deleteConversationConfirm: '确定永久删除此对话吗？', conversationTitle: '对话标题', saveTitle: '保存标题', cancel: '取消',
    theme: '主题', language: '语言', light: '浅色', dark: '深色', system: '跟随系统', english: 'English', chinese: '中文',
    newConversation: '新建对话', connected: '已连接至', preferences: '模型设置', hidePreferences: '收起设置',
    settingsCopy: '这些选项会随每次回复发送。API Key 仅保留在当前浏览器标签页。', provider: '服务商', model: '模型', baseUrl: '基础地址', apiKey: 'API Key', serverDefault: '使用服务端默认值', optionalEndpoint: '可选的服务商地址', tabOnly: '仅在当前标签页保留', knowledgeRetrieval: '知识库检索', knowledgeHint: '为回复加入匹配的 RAG 参考', styleReference: '风格参考', styleHint: '应用已选择的风格语料', temperature: '随机性',
    welcomeTitle: '今天的心情如何？', welcomeText: '您可以从一个问题、一段感受，或一件正在心里的小事开始。', talkPrompt: '梳理一下感受', planPrompt: '规划下一步', composer: '和 Serenova 聊聊',
    stillWaiting: '模型仍在处理请求。您可以停止本次回复，无需刷新页面。', stopGenerating: '停止生成', requestCancelled: '已停止生成。', emptyResponse: '模型已结束响应，但没有返回任何文本。', replyFailed: '暂时无法生成回复。', retryGeneration: '重新生成', copyReply: '复制回复', copied: '已复制回复。', copyFailed: '无法复制回复。', error_provider_api_key_missing: '当前服务商未配置 API Key。', error_provider_authentication: '服务商拒绝了凭据，请检查 API Key。', error_provider_rate_limit: '服务商当前限流，请稍后重试。', error_provider_timeout: '服务商请求超时，请重试。', error_provider_network: '服务商网络连接失败，请重试。', error_provider_server: '服务商暂时不可用，请重试。', error_local_model_failed: '本地模型未能完成回复，请重试。', error_rate_limit_exceeded: '当前账号已达到请求频率限制，请稍后重试。', error_daily_budget_exceeded: '今日 API 预算已达到上限。', error_monthly_budget_exceeded: '本月 API 预算已达到上限。', error_provider_not_supported: '当前选择的服务商不受支持。', error_generation_failed: '模型未能完成回复，请重试。',
    loginTitle: '留一处安静思考的空间。', loginText: '在由您掌控的记忆、知识与个人上下文中继续对话。', welcomeBack: '欢迎回来', loginHelp: '登录后进入您的私密工作区。', userId: '用户 ID', password: '访问密码', signIn: '登录',
    refresh: '刷新', loading: '加载中', save: '保存记录', delete: '删除', upload: '上传', rebuild: '重建', search: '检索', runEvaluation: '运行评估', downloadExport: '下载导出文件', deleteMyData: '删除我的数据', jobs: '后台作业', noJobs: '暂无后台作业。', queued: '排队中', running: '执行中', succeeded: '已完成', failed: '失败', jobQueued: '已提交到后台队列。',
    memoryTitle: '个人数据', memoryDescription: '透明查看当前可供助手参考的记忆内容。', memoryQuality: '记忆质量', stableProfile: '稳定资料', longTermMemory: '长期记忆', longTermDescription: '查看、修正、添加或删除助手可能参考的长期信息。', addMemory: '添加记忆', editMemory: '编辑记忆', deleteMemory: '删除记忆', saveMemory: '保存记忆', memoryText: '记忆内容', memoryRequired: '记忆内容不能为空。', noLongTerm: '暂无长期记忆。', recentEvents: '最近记忆事件', noStable: '暂无稳定资料。', noEvents: '暂无记忆事件。',
    moodTitle: '心情记录', moodDescription: '记录今天的一点感受，并通过一周趋势发现变化。', todayCheckin: '今天的记录', moodLabel: '心情', moodPlaceholder: '例如：平静、焦虑、充满希望', intensity: '强度', note: '备注', notePlaceholder: '可选的背景说明', weeklyTrend: '一周心情趋势', recentCheckins: '最近记录', noCheckins: '暂无记录。',
    noWeeklySummary: '暂无一周总结。', noQualityResult: '暂无质量结果。', noMatchingChunks: '没有匹配的知识片段。', noEvaluation: '暂无已保存的评估报告。',
    history: '对话历史', emotion: '情绪记忆', longTerm: '长期记忆', interests: '兴趣记忆',
    knowledgeTitle: '知识库与 RAG', knowledgeDescription: '查看索引文档，测试检索，并运行已保存的评估集。', status: '状态', documents: '文档', quality: '质量', chunks: '片段', release: '发布', releaseGate: '发布门槛', indexedDocuments: '已索引文档', qualityReport: '质量报告', noDocuments: '暂无已索引文档。', retrievalCheck: '检索测试', retrievalPlaceholder: '输入问题以测试检索效果', ragEvaluation: 'RAG 评估',
    operationsTitle: '运维仪表盘', operationsDescription: '查看本次部署的 API 稳定性、服务商异常、后台作业与告警状态。', selectedWindow: '统计窗口', requests: '请求数', failureRate: '失败率', averageLatency: '平均延迟', activeAlerts: '活跃告警', alerts: '告警', providerFailures: '服务商失败', jobFailures: '后台作业失败', noAlerts: '暂无活跃或近期告警。', noProviderFailures: '当前统计窗口内没有服务商失败。', noJobFailures: '当前统计窗口内没有后台作业失败。', accessDenied: '当前账号没有查看运维数据的权限。',
    privacyTitle: '隐私与导出', privacyDescription: '查看账号存储内容、创建可携带导出，或永久删除数据。', exportTitle: '导出您的数据', exportDescription: '以 JSON 下载会话、记忆、心情记录和其他用户数据；不会导出访问密码、API Key 或 .env 密钥。', deleteTitle: '删除全部数据', deleteDescription: '这会删除当前用户的全部存储数据，不会影响共享知识库文档。', deletePlaceholder: '输入 DELETE 以确认。',
  },
}

export function translate(locale, key) {
  return messages[locale]?.[key] || messages.en[key] || key
}
